"""
Module 2: Fine-Tuning
======================
Adapt a pre-trained model to specific tasks or domains by retraining
on targeted datasets for higher accuracy and relevance.

This module demonstrates LoRA (Low-Rank Adaptation) fine-tuning — the
industry-standard parameter-efficient technique that:
  • Injects small trainable rank-decomposition matrices into the model
  • Freezes the original weights (only ~0.1% of params are trained)
  • Produces a task-specific adapter that can be merged or swapped

Here we fine-tune DistilGPT-2 (82 M params) on a small synthetic
dataset of radio-style news intros to show the before/after shift
in generation style.  The same LoRA config translates directly to
larger models (LLaMA, Mistral, etc.) — only the base_model changes.

Run standalone
--------------
  python -m modules.m2_fine_tune

Requirements (separate from the core POC)
------------------------------------------
  pip install transformers torch peft datasets accelerate
"""

from __future__ import annotations

import json
import os
import sys
import textwrap
from pathlib import Path
from typing import List

# ── Synthetic training corpus ─────────────────────────────────────────────────
# In production this would be replaced with domain-specific data collected
# by the pipeline (curated summaries generated by Module 4 over time).

TRAINING_EXAMPLES: List[str] = [
    "Welcome to AI Tech Radio! Today: HuggingFace releases Transformers 5.0 with native quantisation support, slashing memory requirements by 40%. In React news, the core team shipped Server Actions GA, making full-stack React a first-class citizen.",
    "You're listening to AI Tech Radio. Breaking story: Meta open-sources Llama 3.2 with multimodal capabilities. Meanwhile, React 19 introduces the `use` hook for seamless async data fetching directly in components.",
    "Good morning, developers! AI Tech Radio here. Today's highlight: Mistral drops Mixtral 8x22B — a mixture-of-experts model that rivals GPT-4 on benchmarks at a fraction of the cost. On the front-end, Vite 6 cuts cold-start times in half.",
    "AI Tech Radio, let's go! The open-source community delivered again: LangChain 0.3 ships a unified streaming API across all LLM providers. React developers are excited about the new Compiler that automatically applies memoisation.",
    "This is AI Tech Radio — your daily developer briefing. ChromaDB 0.5 launches with multi-tenant support, unlocking enterprise-grade RAG deployments. Next.js 15 drops partial prerendering into stable, blending static and dynamic seamlessly.",
    "Welcome back to AI Tech Radio! Big news in the embeddings world: Nomic AI's text-embed-v2 beats OpenAI Ada on MTEB benchmarks while being fully open-source. React Native 0.74 lands with a new architecture enabled by default.",
    "AI Tech Radio on the air! Today: Ollama reaches 50 K GitHub stars, cementing local LLM inference as mainstream. The Remix team merges with React Router, simplifying the full-stack React ecosystem.",
    "You're tuned to AI Tech Radio. Google DeepMind releases Gemma 2 in 9B and 27B sizes, immediately topping open-source leaderboards. On the React side, Storybook 8 drops with first-class support for React Server Components.",
    "AI Tech Radio — start your engines! OpenAI's structured outputs feature makes JSON schema adherence reliable, transforming agentic pipelines. Tailwind CSS v4 alpha arrives with a Rust-powered engine, 10x faster builds.",
    "Good evening from AI Tech Radio. Anthropic publishes research on constitutional AI improvements in Claude 3.5. The React ecosystem welcomes TanStack Router v1 stable, bringing type-safe routing to the mainstream.",
    "AI Tech Radio, always on! Stability AI open-sources Stable Diffusion 3, setting a new bar for image generation. TypeScript 5.6 ships with isolated declarations for faster monorepo builds.",
    "This is AI Tech Radio! News from the agents front: AutoGen 0.4 redesigns its architecture around async event-driven workflows. Zustand 5 ships with a slimmer API, keeping React state management dead simple.",
    "AI Tech Radio here with your briefing! Cohere releases Command R+ optimised for RAG with 128K context. The React team publishes their 2024 roadmap, highlighting improvements to Suspense and concurrent rendering.",
    "Welcome to AI Tech Radio — your signal for everything ML and JS. Mistral AI launches Le Chat Enterprise, their private cloud offering. Remix 3 goes all-in on Vite, becoming the fastest React framework in cold-start benchmarks.",
    "AI Tech Radio signing on! Axolotl 1.0 makes fine-tuning large models accessible on consumer GPUs. Meanwhile, the Biome linter hits 1.0 stable, offering a single Rust-based tool for formatting and linting React codebases.",
]


def create_dataset_file(output_path: str = "data/finetune_dataset.jsonl") -> str:
    """Persist the training examples to disk in JSONL format."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        for example in TRAINING_EXAMPLES:
            f.write(json.dumps({"text": example}) + "\n")
    print(f"  ✓ Dataset saved: {out} ({len(TRAINING_EXAMPLES)} examples)")
    return str(out)


def run_finetune_demo(
    base_model: str = "distilgpt2",
    output_dir: str = "output/finetuned_model",
    num_train_steps: int = 30,
) -> None:
    """
    Fine-tune `base_model` using LoRA (PEFT) on the radio-style dataset.
    Prints before/after generation samples to show the style shift.

    Parameters
    ----------
    base_model       : HuggingFace model ID or local path
    output_dir       : where to save the fine-tuned adapter weights
    num_train_steps  : training steps — 30 is enough to see style shift on CPU
    """
    # ── Lazy imports (optional deps) ─────────────────────────────────────────
    try:
        import torch
        from datasets import Dataset
        from peft import LoraConfig, TaskType, get_peft_model
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            DataCollatorForLanguageModeling,
            Trainer,
            TrainingArguments,
        )
    except ImportError:
        print(
            "\n  ⚠  Fine-tuning dependencies not installed.\n"
            "     Run: pip install transformers torch peft datasets accelerate\n"
        )
        return

    print(f"\n{'='*60}")
    print("  MODULE 2: LoRA Fine-Tuning Demo")
    print(f"{'='*60}")
    print(f"  Base model      : {base_model}")
    print(f"  Training steps  : {num_train_steps}")
    print(f"  Dataset size    : {len(TRAINING_EXAMPLES)} radio-style examples")
    print(f"  Technique       : LoRA (Low-Rank Adaptation via PEFT)")
    print()

    # ── Load tokeniser and model ──────────────────────────────────────────────
    print("  Loading tokeniser and base model...")
    tokenizer = AutoTokenizer.from_pretrained(base_model)
    tokenizer.pad_token = tokenizer.eos_token

    base = AutoModelForCausalLM.from_pretrained(base_model)
    base.config.pad_token_id = tokenizer.eos_token_id

    # ── Before fine-tuning ────────────────────────────────────────────────────
    test_prompt = "Welcome to AI Tech Radio! Today's top story:"
    print("\n  ── BEFORE fine-tuning ──────────────────────────────────────")
    before_text = _generate(base, tokenizer, test_prompt, max_new_tokens=60)
    print(textwrap.fill(f"  {before_text}", width=70, subsequent_indent="  "))

    # ── LoRA configuration ────────────────────────────────────────────────────
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=8,               # rank — small rank = fewer trainable params
        lora_alpha=16,     # scaling factor
        lora_dropout=0.1,
        target_modules=["c_attn"],   # GPT-2 attention projection
        bias="none",
    )
    model = get_peft_model(base, lora_config)

    trainable, total = model.get_nb_trainable_parameters()
    print(f"\n  LoRA trainable params : {trainable:,}  ({100*trainable/total:.2f}% of total)")

    # ── Dataset ───────────────────────────────────────────────────────────────
    raw_dataset = Dataset.from_list([{"text": t} for t in TRAINING_EXAMPLES])

    def tokenize(batch):
        return tokenizer(
            batch["text"],
            truncation=True,
            max_length=128,
            padding="max_length",
        )

    tokenized = raw_dataset.map(tokenize, batched=True, remove_columns=["text"])

    # ── Training ──────────────────────────────────────────────────────────────
    args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=max(1, num_train_steps // len(TRAINING_EXAMPLES) + 1),
        max_steps=num_train_steps,
        per_device_train_batch_size=2,
        learning_rate=3e-4,
        logging_steps=10,
        save_strategy="no",
        report_to="none",
        no_cuda=not torch.cuda.is_available(),
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tokenized,
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )

    print(f"\n  Training for {num_train_steps} steps...")
    trainer.train()
    print("  Training complete.")

    # ── After fine-tuning ─────────────────────────────────────────────────────
    print("\n  ── AFTER fine-tuning ───────────────────────────────────────")
    after_text = _generate(model, tokenizer, test_prompt, max_new_tokens=60)
    print(textwrap.fill(f"  {after_text}", width=70, subsequent_indent="  "))

    # ── Save adapter ──────────────────────────────────────────────────────────
    os.makedirs(output_dir, exist_ok=True)
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"\n  ✓ LoRA adapter saved to: {output_dir}")
    print(f"  ✓ Load later: model = AutoModelForCausalLM.from_pretrained('{output_dir}')")


def _generate(model, tokenizer, prompt: str, max_new_tokens: int = 60) -> str:
    import torch
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            pad_token_id=tokenizer.eos_token_id,
        )
    return tokenizer.decode(out[0], skip_special_tokens=True)


# ── LoRA config reference (for documentation / larger models) ─────────────────

LORA_CONFIG_REFERENCE = {
    "llama3_2_1b": {
        "base_model": "meta-llama/Llama-3.2-1B",
        "task_type": "CAUSAL_LM",
        "r": 16,
        "lora_alpha": 32,
        "lora_dropout": 0.05,
        "target_modules": ["q_proj", "v_proj"],
        "bias": "none",
        "trainable_params_approx": "~8M  (0.8% of total)",
        "use_case": "Radio-style script generation fine-tuning",
    },
    "mistral_7b": {
        "base_model": "mistralai/Mistral-7B-v0.1",
        "task_type": "CAUSAL_LM",
        "r": 16,
        "lora_alpha": 32,
        "lora_dropout": 0.05,
        "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj"],
        "bias": "none",
        "trainable_params_approx": "~40M  (0.6% of total)",
        "use_case": "High-quality radio script generation",
    },
}


# ── CLI entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Creating fine-tuning dataset...")
    create_dataset_file()
    print("\nStarting LoRA fine-tuning demo on DistilGPT-2...")
    run_finetune_demo()
